# Generated by Django 4.2.3 on 2023-07-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoaction',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='slug'),
        ),
        migrations.AlterUniqueTogether(
            name='todoaction',
            unique_together={('todo', 'slug')},
        ),
    ]
